export const data = [
  {
    name: "BRSH",
    fullName: "Bruush Oral Care Inc.",
    industry: "Household & Personal Products",
    marketCap: "326.87K",
  },
  {
    name: "CNXA",
    fullName: "Connexa Sports Technologies Inc.",
    industry: "Leisure",
    marketCap: "390.86K",
  },
  {
    name: "KBNT",
    fullName: "Kubient, Inc.",
    industry: "Software - Application",
    marketCap: "408.67K",
  },
  {
    name: "BSFC",
    fullName: "Blue Star Foods Corp.",
    industry: "Packaged Foods",
    marketCap: "483.13K",
  },
  {
    name: "RNAZ",
    fullName: "TransCode Therapeutics, Inc.",
    industry: "Biotechnology",
    marketCap: "531.54K",
  },
  {
    name: "KTRA",
    fullName: "Kintara Therapeutics, Inc.",
    industry: "Biotechnology",
    marketCap: "557.11K",
  },
  {
    name: "CRKN",
    fullName: "Crown ElectroKinetics Corp.",
    industry: "Specialty Chemicals",
    marketCap: "570.20K",
  },
  {
    name: "NEPT",
    fullName: "Neptune Wellness Solutions Inc.",
    industry: "Drug Manufacturers - Specialty & Generic",
    marketCap: "575.76K",
  },
  {
    name: "WHLR",
    fullName: "Wheeler Real Estate Investment Trust, Inc.",
    industry: "REIT - Retail",
    marketCap: "726.27K",
  },
  {
    name: "WISA",
    fullName: "WiSA Technologies, Inc.",
    industry: "Semiconductors",
    marketCap: "871.19K",
  },
  {
    name: "AGRI",
    fullName: "AgriFORCE Growing Systems Ltd.",
    industry: "Farm Products",
    marketCap: "921.04K",
  },
  {
    name: "ADTX",
    fullName: "Aditxt, Inc.",
    industry: "Biotechnology",
    marketCap: "941.08K",
  },
  {
    name: "VERB",
    fullName: "Verb Technology Company, Inc.",
    industry: "Software - Application",
    marketCap: "970.94K",
  },
  {
    name: "SMFL",
    fullName: "Smart for Life, Inc.",
    industry: "Packaged Foods",
    marketCap: "1.05M",
  },
  {
    name: "CPHI",
    fullName: "China Pharma Holdings, Inc.",
    industry: "Drug Manufacturers - Specialty & Generic",
    marketCap: "1.06M",
  },
  {
    name: "MOBQ",
    fullName: "Mobiquity Technologies, Inc.",
    industry: "Advertising Agencies",
    marketCap: "1.06M",
  },
  {
    name: "NUWE",
    fullName: "Nuwellis, Inc.",
    industry: "Medical Devices",
    marketCap: "1.09M",
  },
  {
    name: "RSLS",
    fullName: "ReShape Lifesciences Inc.",
    industry: "Medical Devices",
    marketCap: "1.29M",
  },
];
